const lines = [
   {
    name: "吾妻線",
    color: "#008689",
    file: "lines/agatsuma-line.html",
    stationOrder: [
      "stations/shibukawa.html",
      "stations/kanashima.html",
      "stations/ubashima.html",
      "stations/onogami.html",
      "stations/onogamionsen.html",
      "stations/ichishiro.html",
      "stations/nakanojo.html",
      "stations/gummaharamachi.html",
      "stations/gobara.html",
      "stations/yagura.html",
      "stations/iwashima.html",
      "stations/kawarayuonsen.html",
      "stations/naganoharakusatsuguchi.html",
      "stations/gummaotsu.html",
      "stations/haneo.html",
      "stations/fukurogura.html",
      "stations/manzakazawaguchi.html",
      "stations/omae.html"
    ]
  }
  {
    name: "只見線",
    color: "#0081B8",
    file: "lines/tadami-line.html",
    stationOrder: [
      "stations/aizuwakamatsu.html",
      "stations/nanukamachi.html",
      "stations/nishiwakamatsu.html",
      "stations/aizuhongo.html",
      "stations/aizutakada.html",
      "stations/negishifukushima.html",
      "stations/nitsuru.html",
      "stations/wakamiya.html",
      "stations/aizubange.html",
      "stations/todera.html",
      "stations/aizusakamoto.html",
      "stations/aizuyanaizu.html",
      "stations/godo.html",
      "stations/takiya.html",
      "stations/aizuhinohara.html",
      "stations/aizunishikata.html",
      "stations/aizumiyashita.html",
      "stations/hayato.html",
      "stations/aizumizunuma.html",
      "stations/aizunakagawa.html",
      "stations/aizukawaguchi.html",
      "stations/honna.html",
      "stations/aizukosugawa.html",
      "stations/aizuyokota.html",
      "stations/aizuoshio.html",
      "stations/aizushiozawa.html",
      "stations/aizugamo.html",
      "stations/tadami.html",
      "stations/oshirakawa.html",
      "stations/irihirose.html",
      "stations/kamijo.html",
      "stations/echigosuhara.html",
      "stations/uonumatanaka.html",
      "stations/echigohirose.html",
      "stations/yabukami.html",
      "stations/koide.html"
    ]
  }
];
