const lines = [
   {
    name: "吾妻線",
    kana: "あがつません",
    roman: "Agatsuma-Line",
    color: "#008689",
    icon: "numbering/Agatsuma.png",
    file: "lines/agatsuma-line.html",
    stationOrder: [
      "stations/agatsuma/shibukawa.html",
      "stations/agatsuma/kanashima.html",
      "stations/agatsuma/ubashima.html",
      "stations/agatsuma/onogami.html",
      "stations/agatsuma/onogamionsen.html",
      "stations/agatsuma/ichishiro.html",
      "stations/agatsuma/nakanojo.html",
      "stations/agatsuma/gummaharamachi.html",
      "stations/agatsuma/gobara.html",
      "stations/agatsuma/yagura.html",
      "stations/agatsuma/iwashima.html",
      "stations/agatsuma/kawarayuonsen.html",
      "stations/agatsuma/naganoharakusatsuguchi.html",
      "stations/agatsuma/gummaotsu.html",
      "stations/agatsuma/haneo.html",
      "stations/agatsuma/fukurogura.html",
      "stations/agatsuma/manzakazawaguchi.html",
      "stations/agatsuma/omae.html"
    ]
   },
   {
    name: "左沢線",
    kana: "あてらざわせん",
    roman: "Aterazawa-Line",
    color: "#0072BA",
    icon: "numbering/Aterazawa.png",
    file: "lines/aterazawa-line.html",
    stationOrder: [
      "stations/aterazawa/yamagata.html",
      "stations/aterazawa/kitayamagata.html",
      "stations/aterazawa/higashikanai.html",
      "stations/aterazawa/uzenyamabe.html",
      "stations/aterazawa/uzenkanezawa.html",
      "stations/aterazawa/uzennagasaki.html",
      "stations/aterazawa/minamisagae.html",
      "stations/aterazawa/sagae.html",
      "stations/aterazawa/nishisagae.html",
      "stations/aterazawa/uzentakamatsu.html",
      "stations/aterazawa/shibahashi.html",
      "stations/aterazawa/aterazawa.html"
    ]
   },
   {
    name: "飯山線",
    kana: "いいやません",
    roman: "Iiyama-Line",
    color: "#5BBB24",
    icon: "numbering/Iiyama.png",
    file: "lines/iiyama-line.html",
    stationOrder: [
      "stations/iiyama/nagano.html",
      "stations/iiyama/kitanagano.html",
      "stations/iiyama/sansai.html",
      "stations/iiyama/toyono.html",
      "stations/iiyama/shinanoasano.html",
      "stations/iiyama/tategahana.html",
      "stations/iiyama/kamiimai.html",
      "stations/iiyama/kaesa.html",
      "stations/iiyama/hachisu.html",
      "stations/iiyama/iiyama.html",
      "stations/iiyama/kitaiiyama.html",
      "stations/iiyama/shinanotaira.html",
      "stations/iiyama/togarinozawaonsen.html",
      "stations/iiyama/kamisakai.html",
      "stations/iiyama/kamikuwanagawa.html",
      "stations/iiyama/kuwanagawa.html",
      "stations/iiyama/ishiotaki.html",
      "stations/iiyama/shinanoshiratori.html",
      "stations/iiyama/hirataki.html",
      "stations/iiyama/yokokura.html",
      "stations/iiyama/morimiyanohara.html",
      "stations/iiyama/ashidaki.html",
      "stations/iiyama/echigotanaka.html",
      "stations/iiyama/tsunan.html",
      "stations/iiyama/echigoshikawatari.html",
      "stations/iiyama/echigotazawa.html",
      "stations/iiyama/echigomizusawa.html",
      "stations/iiyama/doichi.html",
      "stations/iiyama/tokamachi.html",
      "stations/iiyama/uonumanakajo.html",
      "stations/iiyama/gejo.html",
      "stations/iiyama/echigoiwasawa.html",
      "stations/iiyama/uchigamaki.html",
      "stations/iiyama/echigokawaguchi.html"
    ]
   },
   {
    name: "石巻線",
    kana: "いしのまきせん",
    roman: "Ishinomaki-Line",
    color: "#F76F99",
    icon: "numbering/Ishinomaki.png",
    file: "lines/ishinomaki-line.html",
    stationOrder: [
      "stations/ishinomaki/kogota.html",
      "stations/ishinomaki/kamiwakuya.html",
      "stations/ishinomaki/wakuya.html",
      "stations/ishinomaki/maeyachi.html",
      "stations/ishinomaki/kakeyama.html",
      "stations/ishinomaki/kanomata.html",
      "stations/ishinomaki/sobanokami.html",
      "stations/ishinomaki/ishinomaki.html",
      "stations/ishinomaki/rikuzeninai.html",
      "stations/ishinomaki/watanoha.html",
      "stations/ishinomaki/mangokuura.html",
      "stations/ishinomaki/sawada.html",
      "stations/ishinomaki/urashuku.html",
      "stations/ishinomaki/onagawa.html"
    ]
   },
   {
    name: "五日市線",
    kana: "いつかいちせん",
    roman: "Itsukaichi-Line",
    color: "#EB5C01",
    icon: "numbering/Chuo.png",
    file: "lines/itsukaichi-line.html",
    stationOrder: [
      "stations/itsukaichi/haijima.html",
      "stations/itsukaichi/kumagawa.html",
      "stations/itsukaichi/higashiakiru.html",
      "stations/itsukaichi/akigawa.html",
      "stations/itsukaichi/musashihikida.html",
      "stations/itsukaichi/musashimasuko.html",
      "stations/itsukaichi/musashiitsukaichi.html"
    ]
   },
   {
    name: "伊東線",
    kana: "いとうせん",
    roman: "Itō-Line",
    color: "#378640",
    file: "lines/ito-line.html",
    stationOrder: [
      "stations/tokaido/atami.html",
      "stations/ito/kinomiya.html",
      "stations/ito/izutaga.html",
      "stations/ito/ajiro.html",
      "stations/ito/usami.html",
      "stations/ito/ito.html"
    ]
   },
   {
    name: "羽越本線",
    kana: "うえつほんせん",
    roman: "Uetsu-Line",
    color: "#00B9DB",
    icon: "numbering/Uetsu.png",
    file: "lines/uetsu-line.html",
    stationOrder: [
      "stations/nitsu.html",
      "stations/kyogase.html",
      "stations/mizuhara.html",
      "stations/kamiyama.html",
      "stations/tsukioka.html",
      "stations/nakaura.html",
      "stations/shibata.html",
      "stations/kaji.html",
      "stations/kanazuka.html",
      "stations/nakajo.html",
      "stations/hirakida.html",
      "stations/sakamachi.html",
      "stations/hirabayashi.html",
      "stations/iwahunemachi.html",
      "stations/murakami.html",
      "stations/majima.html",
      "stations/echigohayakawa.html",
      "stations/kuwagawa.html",
      "stations/imagawa.html",
      "stations/echigokangawa.html",
      "stations/gatsugi.html",
      "stations/fuya.html",
      "stations/nezugaseki.html",
      "stations/koiwagawa.html",
      "stations/atsumionsen.html",
      "stations/iragawa.html",
      "stations/kobato.html",
      "stations/sanze.html",
      "stations/uzenmizusawa.html",
      "stations/uzenoyama.html",
      "stations/tsuruoka.html",
      "stations/fujishima.html",
      "stations/nishibukuro.html",
      "stations/amarume.html",
      "stations/kitaamarume.html",
      "stations/sagoshi.html",
      "stations/higashisakata.html",
      "stations/sakata.html",
      "stations/mototate.html",
      "stations/minamichokai.html",
      "stations/yuza.html",
      "stations/fukura.html",
      "stations/mega.html",
      "stations/kosagawa.html",
      "stations/kamihama.html",
      "stations/kisakata.html",
      "stations/konoura.html",
      "stations/nikaho.html",
      "stations/nishime.html",
      "stations/ugohonjo.html",
      "stations/ugoiwaya.html",
      "stations/oriwatari.html",
      "stations/ugokameda.html",
      "stations/iwakiminato.html",
      "stations/michikawa.html",
      "stations/shimohama.html",
      "stations/katsurane.html",
      "stations/araya.html",
      "stations/ugoushijima.html",
      "stations/akita.html"
    ]
   },
   {
    name: "内房線",
    kana: "うちぼうせん",
    roman: "Uchibo-Line",
    color: "#0071C5",
    icon: "numbering/Uchibo.png",
    file: "lines/uchibo-line.html",
    stationOrder: [
      "stations/chiba.html",
      "stations/honchiba.html",
      "stations/soga.html",
      "stations/hamano.html",
      "stations/yawatajuku.html",
      "stations/goi.html",
      "stations/anegasaki.html",
      "stations/nagaura.html",
      "stations/sodegaura.html",
      "stations/iwane.html",
      "stations/kisarazu.html",
      "stations/kimitsu.html",
      "stations/aohori.html",
      "stations/onuki.html",
      "stations/sanukimachi.html",
      "stations/kazusaminato.html",
      "stations/takeoka.html",
      "stations/hamakanaya.html",
      "stations/hota.html",
      "stations/awakatsuyama.html",
      "stations/iwai.html",
      "stations/tomiura.html",
      "stations/nakofunakata.html",
      "stations/tateyama.html",
      "stations/kokonoe.html",
      "stations/chikura.html",
      "stations/chitose.html",
      "stations/minamihara.html",
      "stations/wadaura.html",
      "stations/emi.html",
      "stations/futomi.html",
      "stations/awakamogawa.html"
    ]
   },
   {
    name: "宇都宮線",
    kana: "うつのみやせん",
    roman: "Utsunomiya-Line",
    color: "#FF9845",
    file: "lines/utsunomiya-line.html",
    stationOrder: [
      "stations/tokyo.html",
      "stations/ueno.html",
      "stations/oku.html",
      "stations/akabane.html",
      "stations/urawa.html",
      "stations/saitamashintoshin.html",
      "stations/omiya.html",
      "stations/toro.html",
      "stations/higashiomiya.html",
      "stations/hasuda.html",
      "stations/shiraoka.html",
      "stations/shinshiraoka.html",
      "stations/kuki.html",
      "stations/higashiwashinomiya.html",
      "stations/kurihashi.html",
      "stations/koga.html",
      "stations/nogi.html",
      "stations/mamada.html",
      "stations/oyama.html",
      "stations/koganei.html",
      "stations/jichiidai.html",
      "stations/ishibashi.html",
      "stations/suzumenomiya.html",
      "stations/utsunomiya.html",
      "stations/okamoto.html",
      "stations/hoshakuji.html",
      "stations/ujiie.html",
      "stations/kamasusaka.html",
      "stations/kataoka.html",
      "stations/yaita.html",
      "stations/nozaki.html",
      "stations/nishinasuno.html",
      "stations/nasushiobara.html",
      "stations/kuroiso.html"
    ]
   },
   {
    name: "越後線",
    kana: "えちごせん",
    roman: "Echigo-Line",
    color: "#378640",
    icon: "numbering/Echigo.png",
    file: "lines/echigo-line.html",
    stationOrder: [
      "stations/kashiwazaki.html",
      "stations/higashikashiwazaki.html",
      "stations/nishinakadori.html",
      "stations/arahama.html",
      "stations/kariwa.html",
      "stations/nishiyama.html",
      "stations/raihai.html",
      "stations/ishiji.html",
      "stations/oginojo.html",
      "stations/izumozaki.html",
      "stations/myohoji.html",
      "stations/ojimaya.html",
      "stations/kirihara.html",
      "stations/teradomari.html",
      "stations/bunsui.html",
      "stations/aozu.html",
      "stations/minamiyoshida.html",
      "stations/yoshida.html",
      "stations/kitayoshida.html",
      "stations/iwamuro.html",
      "stations/maki.html",
      "stations/echigosone.html",
      "stations/echigoakatsuka.html",
      "stations/uchinonishigaoka.html",
      "stations/uchino.html",
      "stations/nigatadaigakumae.html",
      "stations/terao.html",
      "stations/kobari.html",
      "stations/aoyama.html",
      "stations/sekiya.html",
      "stations/hakusan.html",
      "stations/kamitokoro.html",
      "stations/nigata.html"
    ]
   },
   {
    name: "奥羽本線",
    kana: "おううほんせん",
    roman: "Ōu-Line",
    color: "#FF7E1C",
    icon: "numbering/Ou.png",
    file: "lines/ou-line.html",
    stationOrder: [
      "stations/fukushima.html",
      "stations/sasakino.html",
      "stations/niwasaka.html",
      "stations/itaya.html",
      "stations/toge.html",
      "stations/osawa.html",
      "stations/sekine.html",
      "stations/yonezawa.html",
      "stations/oitama.html",
      "stations/takahata.html",
      "stations/akayu.html",
      "stations/nakagawa.html",
      "stations/uzennakayama.html",
      "stations/kaminoyamaonsen.html",
      "stations/mokichikinenkammae.html",
      "stations/zao.html",
      "stations/yamagata.html",
      "stations/kitayamagata.html",
      "stations/uzenchitose.html",
      "stations/minamidewa.html",
      "stations/urushiyama.html",
      "stations/takatama.html",
      "stations/tendominami.html",
      "stations/tendo.html",
      "stations/midaregawa.html",
      "stations/jimmachi.html",
      "stations/sakuranbohigashine.html",
      "stations/higashine.html",
      "stations/murayama.html",
      "stations/sodesaki.html",
      "stations/oishida.html",
      "stations/kitaoishida.html",
      "stations/ashizawa.html",
      "stations/funakata.html",
      "stations/shinjo.html",
      "stations/izumita.html",
      "stations/uzentoyosato.html",
      "stations/mamurogawa.html",
      "stations/kamabuchi.html",
      "stations/otaki.html",
      "stations/nozoki.html",
      "stations/innai.html",
      "stations/yokohori.html",
      "stations/mitsuseki.html",
      "stations/kamiyuzawa.html",
      "stations/yuzawa.html",
      "stations/shimoyuzawa.html",
      "stations/jumonji.html",
      "stations/daigo.html",
      "stations/yanagita.html",
      "stations/yokote.html",
      "stations/gosannen.html",
      "stations/izume.html",
      "stations/omagari.html",
      "stations/jinguji.html",
      "stations/kariwano.html",
      "stations/mineyoshikawa.html",
      "stations/ugosakai.html",
      "stations/obarino.html",
      "stations/wada.html",
      "stations/yotsugoya.html",
      "stations/akita.html",
      "stations/izumisotoasahikawa.html",
      "stations/tsuchizaki.html",
      "stations/kamiijima.html",
      "stations/oiwake.html",
      "stations/okubo.html",
      "stations/ugoizuka.html",
      "stations/ikawasakura.html",
      "stations/hachirogata.html",
      "stations/koikawa.html",
      "stations/kado.html",
      "stations/moritake.html",
      "stations/kitakanaoka.html",
      "stations/higashinoshiro.html",
      "stations/tsurugata.html",
      "stations/tomine.html",
      "stations/futatsui.html",
      "stations/maeyama.html",
      "stations/takanosu.html",
      "stations/nukazawa.html",
      "stations/hayaguchi.html",
      "stations/shimokawazoi.html",
      "stations/odate.html",
      "stations/shirasawa.html",
      "stations/jinba.html",
      "stations/tsugaruyunosawa.html",
      "stations/ikarigaseki.html",
      "stations/nagamine.html",
      "stations/owanionsen.html",
      "stations/ishikawa.html",
      "stations/hirosaki.html",
      "stations/naijoshi.html",
      "stations/kawabe.html",
      "stations/kitatokiwa.html",
      "stations/namioka.html",
      "stations/daishaka.html",
      "stations/tsurugasaka.html",
      "stations/tsugarushinjo.html",
      "stations/shinaomori.html",
      "stations/aomori.html"
    ]
   },
   {
    name: "青梅線",
    kana: "おうめせん",
    roman: "Ōme-Line",
    color: "#EB5C01",
    file: "lines/ome-line.html",
    stationOrder: [
      "stations/tachikawa.html",
      "stations/nishitachikawa.html",
      "stations/higashinakagami.html",
      "stations/nakagami.html",
      "stations/akishima.html",
      "stations/haijima.html",
      "stations/ushihama.html",
      "stations/fussa.html",
      "stations/hamura.html",
      "stations/ozaku.html",
      "stations/kabe.html",
      "stations/higashiome.html",
      "stations/ome.html",
      "stations/miyanohira.html",
      "stations/hinatawada.html",
      "stations/ishigamimae.html",
      "stations/futamatao.html",
      "stations/ikusabata.html",
      "stations/sawai.html",
      "stations/mitake.html",
      "stations/kawai.html",
      "stations/kori.html",
      "stations/hatonosu.html",
      "stations/shiromaru.html",
      "stations/okutama.html"
    ]
   },
   {
    name: "大糸線",
    kana: "おおいとせん",
    roman: "Ōito-Line",
    color: "#957490",
    icon: "numbering/Oito.png",
    file: "lines/oito-line.html",
    stationOrder: [
      "stations/matsumoto.html",
      "stations/kitamatsumoto.html",
      "stations/shimauchi.html",
      "stations/shimatakamatsu.html",
      "stations/azusabashi.html",
      "stations/hitoichiba.html",
      "stations/nakagaya.html",
      "stations/minamitoyoshina.html",
      "stations/toyoshina.html",
      "stations/hakuyacho.html",
      "stations/hodaka.html",
      "stations/ariake.html",
      "stations/azumioiwake.html",
      "stations/hosono.html",
      "stations/kitahosono.html",
      "stations/shinanomatsukawa.html",
      "stations/azumikutsukake.html",
      "stations/shinanotokiwa.html",
      "stations/minamiomachi.html",
      "stations/shinanoomachi.html",
      "stations/kitaomachi.html",
      "stations/shinanokizaki.html",
      "stations/inao.html",
      "stations/uminokuchi.html",
      "stations/yanaba.html",
      "stations/minamikamishiro.html",
      "stations/kamishiro.html",
      "stations/imori.html",
      "stations/hakuba.html",
      "stations/shinanomoriue.html",
      "stations/hakubaoike.html",
      "stations/chikuni.html",
      "stations/minamiotari.html"
    ]
   },
   {
    name: "只見線",
    kana: "ただみせん",
    roman: "Tadami-Line",
    color: "#0081B8",
    file: "lines/tadami-line.html",
    stationOrder: [
      "stations/aizuwakamatsu.html",
      "stations/nanukamachi.html",
      "stations/nishiwakamatsu.html",
      "stations/aizuhongo.html",
      "stations/aizutakada.html",
      "stations/negishifukushima.html",
      "stations/nitsuru.html",
      "stations/wakamiya.html",
      "stations/aizubange.html",
      "stations/todera.html",
      "stations/aizusakamoto.html",
      "stations/aizuyanaizu.html",
      "stations/godo.html",
      "stations/takiya.html",
      "stations/aizuhinohara.html",
      "stations/aizunishikata.html",
      "stations/aizumiyashita.html",
      "stations/hayato.html",
      "stations/aizumizunuma.html",
      "stations/aizunakagawa.html",
      "stations/aizukawaguchi.html",
      "stations/honna.html",
      "stations/aizukosugawa.html",
      "stations/aizuyokota.html",
      "stations/aizuoshio.html",
      "stations/aizushiozawa.html",
      "stations/aizugamo.html",
      "stations/tadami.html",
      "stations/oshirakawa.html",
      "stations/irihirose.html",
      "stations/kamijo.html",
      "stations/echigosuhara.html",
      "stations/uonumatanaka.html",
      "stations/echigohirose.html",
      "stations/yabukami.html",
      "stations/koide.html"
    ]
  }
];
