const lines = [
  {
    name: "只見線",
    color: "#0081B8",
    file: "lines/tadami-line.html",
    stationOrder: [
      "stations/aizuwakamatsu.html",
      "stations/nanukamachi.html",
      "stations/nishiwakamatsu.html",
      "stations/aizuhongo.html",
      "stations/aizutakada.html",
      "stations/negishifukushima.html",
      "stations/nitsuru.html",
      "stations/wakamiya.html",
      "stations/aizusakamoto.html",
      "stations/aizuyanaizu.html",
      "stations/godo.html",
      "stations/takiya.html",
      "stations/aizuhinohara.html",
      "stations/aizunishikata.html",
      "stations/aizumiyashita.html",
      "stations/hayato.html",
      "stations/aizumizunuma.html",
      "stations/aizunakagawa.html",
      "stations/aizukawaguchi.html",
      "stations/honna.html",
      "stations/aizukosugawa.html",
      "stations/aizuyokota.html",
      "stations/aizuoshio.html",
      "stations/aizushiozawa.html",
      "stations/aizugamo.html",
      "stations/tadami.html",
      "stations/oshirakawa.html",
      "stations/irihirose.html",
      "stations/kamijo.html",
      "stations/echigosuhara.html",
      "stations/uonumatanaka.html",
      "stations/echigohirose.html",
      "stations/yabukami.html",
      "stations/koide.html"
    ]
  }
];
